operation_class:
   result_yaml_file: 'merged_YAML_file.yaml'

plot_graph:
   fig_size_x: 13
   fig_size_y: 6
   graph_file: 'result_graph.png'
   graph_dpi: 300

send_notify:
   sendEmail: 
   recvEmail: 
   identification: 
   password: 
   smtpName: 
   smtpPort: 465                        # smtp Port Number e.g. 587
   head_msg: "[Notify] NIPS2024 Test work Finish"
   etri_mail: True